In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('https://raw.githubusercontent.com/MiltonDavila2/CSV/refs/heads/main/StudentsPerformance.csv')

In [5]:
print(dataset.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  


In [6]:
#VARIABLES X
X = dataset.iloc[:, dataset.columns!='math score']
#VARIABLES Y
Y = dataset.iloc[:, dataset.columns=='math score']



In [7]:
print(X.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  reading score  writing score  
0                    none             72             74  
1               completed             90             88  
2                    none             95             93  
3                    none             57             44  
4                    none             78             75  


In [8]:
print(Y.head())

   math score
0          72
1          69
2          90
3          47
4          76


In [9]:
#TRANSFORMAMOS LAS VARIABLES DUMMIES A NUMERICAS
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
#VEMOS LO QUE TRANSFORMO
print(X[:5,:])

[[0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 'female' 'standard' 'none'
  72 74]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 'female' 'standard'
  'completed' 90 88]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 'female' 'standard' 'none'
  95 93]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 'male' 'free/reduced'
  'none' 57 44]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 'male' 'standard' 'none' 78
  75]]


In [11]:
#TRANSFORMAMOS LAS VARIABLES DICOTOMICAS
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 11] = le.fit_transform(X[:, 11])
X[:, 12] = le.fit_transform(X[:, 12])
X[:, 13] = le.fit_transform(X[:, 13])

In [12]:
print(X[:5,:])

[[0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0 1 1 72 74]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0 1 0 90 88]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0 1 1 95 93]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1 0 1 57 44]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1 1 1 78 75]]


In [13]:
#Eliminamos una columna para evitar la colinealidad
X = np.delete(X, 0, axis=1) 
X = np.delete(X, 4, axis=1) 

In [14]:
print(X[:5,:])

[[1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0 1 1 72 74]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0 1 0 90 88]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0 1 1 95 93]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1 0 1 57 44]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1 1 1 78 75]]


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state = 0)

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [17]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
Y_test= Y_test.to_numpy() #Esto se elimina si se quiere volver a correr esta linea
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[ 61.99  62.  ]
 [ 74.97  87.  ]
 [ 48.73  40.  ]
 [ 66.53  77.  ]
 [ 69.57  69.  ]
 [ 73.27  78.  ]
 [ 65.06  67.  ]
 [ 48.46  46.  ]
 [ 90.17  99.  ]
 [ 42.21  46.  ]
 [ 44.24  54.  ]
 [ 60.3   53.  ]
 [ 80.53  91.  ]
 [ 85.67  84.  ]
 [ 44.53  48.  ]
 [ 33.05  33.  ]
 [ 57.48  57.  ]
 [ 74.89  81.  ]
 [ 47.35  50.  ]
 [ 80.92  80.  ]
 [ 55.98  63.  ]
 [ 46.57  52.  ]
 [ 72.15  73.  ]
 [ 63.51  66.  ]
 [ 46.57  55.  ]
 [ 64.95  68.  ]
 [ 62.81  65.  ]
 [ 49.78  60.  ]
 [ 56.52  53.  ]
 [ 77.66  69.  ]
 [ 74.11  71.  ]
 [ 90.5   93.  ]
 [ 85.22  82.  ]
 [ 54.66  48.  ]
 [ 42.85  52.  ]
 [ 88.24  92.  ]
 [ 90.27  92.  ]
 [ 57.25  69.  ]
 [ 68.02  57.  ]
 [ 68.75  69.  ]
 [ 71.58  76.  ]
 [ 58.51  62.  ]
 [ 73.02  71.  ]
 [ 67.49  57.  ]
 [ 72.75  71.  ]
 [ 50.27  52.  ]
 [ 82.69  77.  ]
 [ 53.55  59.  ]
 [ 75.16  77.  ]
 [ 51.08  44.  ]
 [ 41.83  47.  ]
 [ 64.06  67.  ]
 [ 42.01  44.  ]
 [ 61.87  61.  ]
 [ 37.45  39.  ]
 [ 65.11  63.  ]
 [ 46.34  47.  ]
 [ 66.52  69.  ]
 [ 84.31  81. 

In [18]:
r2_train = regressor.score(X_train, Y_train)
r2_test = regressor.score(X_test, Y_test)

print("R^2 (Training):", r2_train)
print("R^2 (Testing):", r2_test)

R^2 (Training): 0.8789388438514815
R^2 (Testing): 0.8629895363812148


In [19]:
from sklearn.metrics import mean_absolute_error
mae_train = mean_absolute_error(Y_train, regressor.predict(X_train))
mae_test = mean_absolute_error(Y_test, regressor.predict(X_test))

print("MAE (Training):", mae_train)
print("MAE (Testing):", mae_test)

MAE (Training): 4.227574916494358
MAE (Testing): 4.394842748524528
